# SPDX-FileCopyrightText: 2024 Maxime Roussin-Bélanger <maxime.roussinbelanger@gmail.com>
#
# SPDX-License-Identifier: MIT

SUMMARY = "FutureSQL"
DESCRIPTION = "A non-blocking database framework for Qt"
HOMEPAGE = "https://invent.kde.org/libraries/futuresql"
LICENSE = "(LGPL-2.1-only | LGPL-3.0-only | LicenseRef-KDE-Accepted-LGPL)"
PR = "r0"

DEPENDS += "qcoro"

SRC_URI = "git://invent.kde.org/libraries/${BPN};nobranch=1;protocol=https"
S = "${UNPACKDIR}/git"

inherit cmake_kdeapp
inherit reuse_license_checksums
